import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}



// import React from "react";

// const Hero = () => {
//   return (
//     <>
//       <div className="relative w-full overflow-hidden bg-white pt-10" style={{ height: "770px" }}>
//         <img src="/hero1.jpg" alt="" className="object-cover w-full h-full" />
//         <div className="absolute inset-0 flex justify-center items-center">
//           <div className="text-center">
//             <h1 className="text-4xl font-bold text-white">Your Text Here</h1>
//             <p className="text-lg text-white">Your Subtext Here</p>
//           </div>
//         </div>
//         <div className="absolute inset-0 bg-gradient-to-tr from-gray-400 to-transparent blur" />
//       </div>
//     </>
//   );
// };

// export default Hero;
